name: solar-system workflow

on:
  workflow_dispatch:
  push:
    branches:
      - feature-branch
      - main

env:
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_URI: ${{ vars.MONGO_URI }}

jobs:
  docker:
    name: Containerization
    runs-on: ubuntu-latest
    permissions: 
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Docker Hub login
        uses: docker/login-action@v3.5.0
        with:  
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GHCR login
        uses: docker/login-action@v3.5.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      